### ISSUE TITLE
LagrangePolynomial

### ISSUE THREAD

**Issue by jlapeyre** [PtFEM/NumericalMethodsforEngineers.jl#3]
You might consider modifying `LagrangePolynomial` as follows.  I used `+=` and `*=`, and simplified the `If` expressions. I also initialize `num, den` to integers. The polynomial then will use integer, floating-point, or rational coefficients, depending on the input.
 
```julia
@sym begin
  LagrangePolynomial(xi_, yi_) := Module([N, sum, num, den],
    begin
      N = Length(xi)
      sum = 0
      For( i=1, i <= N, Increment(i),
        begin
          num = 1
          den = 1
          For( j=1, j <= N, Increment(j),
            begin
              If(j != i, num *= (x-xi[j]))
              If(j != i, den *= (xi[i]-xi[j]))
            end
          )
          sum += yi[i] * num/den
        end
      ),
      Return(Simplify(sum))
    end
  )
end
```

**Comment by goedman** [comment]
Thanks John, will update the tests accordingly! Yes, when I did this work I was really focused on just getting it to work (and I will never be a real programmer anyway, just not in my DNA).
