### ISSUE TITLE
NumericalMethodsforEngineers [00e1d38a] is fixed to version 1.1.0

### ISSUE THREAD

**Issue by OVGULIU** [PtFEM/NumericalMethodsforEngineers.jl#7]
Can we use these code for Julia version 1.2.0?

Issue:
**NumericalMethodsforEngineers [00e1d38a] is fixed to version 1.1.0**

**Comment by goedman** [comment]
Thanks for pointing this out. In the queue to be merged in the next couple of hours or so. I'm also trying to see of John would be willing to fix a bunch of warnings when running on Julia 1.4-DEV.

**Comment by goedman** [comment]
Version 1.1.0 has been merged.

**Comment by OVGULIU** [comment]
Thanks! Some issues still remain, i.e.

ERROR: Unsatisfiable requirements detected for package FillArrays :
 FillArrays  log:
 ├─possible versions are: [0.2.0-0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.4, 0.7.0-0.7.3] or uninstalled
 └─restricted to versions [0.8.0-0.8, 0.9.0-0.9] by NumericalMethodsforEngineers [00e1d38a] — no versions left
   └─NumericalMethodsforEngineers  log:
     ├─possible versions are: 1.1.0 or uninstalled
     └─NumericalMethodsforEngineers is fixed to version 1.1.0

**Comment by goedman** [comment]
Is there a reason your version of FillArrays is kept on 0.7?

Can you try to update by in the REPL typing `] up`?

If not, I can lower the lower limit set on FillArrays to 0.7.

**Comment by OVGULIU** [comment]
I have updated FillArrays, but now I find another issue,

ERROR: Unsatisfiable requirements detected for package GR :
 GR log:
 ├─possible versions are: [0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0-0.9.17, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.26.0, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0-0.32.3, 0.33.1, 0.34.0-0.34.1, 0.35.0, 0.36.0, 0.37.0, 0.38.0-0.38.1, 0.39.0-0.39.1, 0.39.99-0.39.100] or uninstalled
 └─restricted to versions [0.42.0-0.42, 0.43.0-0.43] by NumericalMethodsforEngineers  — no versions left
   └─NumericalMethodsforEngineers log:
     ├─possible versions are: 1.1.0 or uninstalled
     └─NumericalMethodsforEngineers [00e1d38a] is fixed to version 1.1.0

**Comment by goedman** [comment]
Hmm, again, I can lower the lower bound for GR but it would be better for you to update GR to 0.44.

Did you upgrade all packages in your Julia 1.2.0 (or just FillArrays)? The command I suggested above should have updated all packages and from above message nothing is holding GR back in your installation.

Let me know if you are able to do a general upgrade or a NumericalMethodsforEngineers package with a lower bound.

One issue is that if you don't update all of your Julia packages, Julia might continue to spit out further incompatibilities one by one.

Rob

**Comment by OVGULIU** [comment]
@goedman now I have installed, thanks!

**Comment by goedman** [comment]
Great. I'll see if John can updates the warnings issue.
